name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.joblabel }}
    runs-on: ${{ matrix.os }}
    env:
      ORBITAL_COVERAGE:    ${{ matrix.coverage }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        coverage: ['']
        include:
          - os: 'ubuntu-latest'
            coverage: coveralls
            joblabel: '(Coverage)'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Orbital Transfer
        shell: bash
        run: |
          eval "$(curl https://raw.githubusercontent.com/orbital-transfer/launch-site/master/script/ci/github-actions-orbital.sh)"
      - name: Use Orbital Transfer
        run: |
          perl -S orbitalism bootstrap auto
          perl -S orbitalism
          perl -S orbitalism test
